export const COMPONENTS = {
  ATTENDENCE: "ATTENDENCE",
  LEAVE: "LEAVE",
  EMPLOYEE_MANAGEMENT: "EMPLOYEE_MANAGEMENT",
  HR_DASHBOARD: "HR_DASHBOARD",
  EMPLOYEE_DASHBOARD: "EMPLOYEE_DASHBOARD",
  LEAVE_APPROVAL: "LEAVE_APPROVAL",
};

export const permissions = {
  ATTENDENCE_VIEW: { permission: "ATTENDENCE_VIEW" },
  ATTENDENCE_CREATE: { permission: "ATTENDENCE_CREATE" },
  LEAVE_VIEW: { permission: "LEAVE_VIEW" },
  EMPLOYEE_MANGEMENT_VIEW: { permission: "EMPLOYEE_MANGEMENT_VIEW" },
  HR_DASHBOARD_VIEW: { permission: "HR_DASHBOARD_VIEW" },
  EMPLOYEE_DASHBOARD_VIEW: { permission: "EMPLOYEE_DASHBOARD_VIEW" },
  LEAVE_APPROVAL_VIEW: { permission: "LEAVE_APPROVAL_VIEW" },
};
